Repository chaeeun-Han/Metanet-Final-Project-Team-2, pull requests merged in 2025-02, with the labels that each got.

#9 [Feature] SMTP를 활용한 이메일 인증 API 구현
  MetanetProject/pom.xml
  MetanetProject/src/main/java/com/example/myapp/config/EmailConfig.java
  MetanetProject/src/main/java/com/example/myapp/config/RedisConfig.java
  MetanetProject/src/main/java/com/example/myapp/member/controller/EmailController.java
  MetanetProject/src/main/java/com/example/myapp/member/controller/MemberController.java
  MetanetProject/src/main/java/com/example/myapp/member/dao/IMemberRepository.java
  MetanetProject/src/main/java/com/example/myapp/member/model/Email.java
  MetanetProject/src/main/java/com/example/myapp/member/service/IMemberService.java
  MetanetProject/src/main/java/com/example/myapp/member/service/MemberService.java
  MetanetProject/src/main/java/com/example/myapp/util/RedisUtil.java
  MetanetProject/src/main/resources/templates/member/mail.html
Labels: feature

#13 [Feature] ResponseEntity common file 생성
  MetanetProject/src/main/java/com/example/myapp/common/response/ResponseCode.java
  MetanetProject/src/main/java/com/example/myapp/common/response/ResponseDto.java
  MetanetProject/src/main/java/com/example/myapp/common/response/ResponseMessage.java
  MetanetProject/src/main/java/com/example/myapp/member/controller/EmailController.java
  MetanetProject/src/main/java/com/example/myapp/member/service/IMemberService.java
  MetanetProject/src/main/java/com/example/myapp/member/service/MemberService.java
Labels: feature, refactor

#16 Sys join 8
  MetanetProject/src/main/java/com/example/myapp/common/response/ResponseCode.java
  MetanetProject/src/main/java/com/example/myapp/common/response/ResponseDto.java
  MetanetProject/src/main/java/com/example/myapp/common/response/ResponseMessage.java
  MetanetProject/src/main/java/com/example/myapp/config/SecurityConfig.java
  MetanetProject/src/main/java/com/example/myapp/jwt/JwtTokenProvider.java
  MetanetProject/src/main/java/com/example/myapp/member/controller/AuthRestController.java
  MetanetProject/src/main/java/com/example/myapp/member/controller/MemberController.java
  MetanetProject/src/main/java/com/example/myapp/member/controller/MemberRestController.java
  MetanetProject/src/main/java/com/example/myapp/member/model/Member.java
  MetanetProject/src/main/java/com/example/myapp/member/model/MemberUserDetailsService.java
  MetanetProject/src/main/java/com/example/myapp/member/service/IMemberService.java
  MetanetProject/src/main/java/com/example/myapp/member/service/MemberUserDetailsService.java
  MetanetProject/src/main/resources/mapper/member/MemberMapper.xml
Labels: feature

#17 [feature] Redis를 활용한 JWT RefreshToken 로그인 구현
  MetanetProject/pom.xml
  MetanetProject/src/main/java/com/example/myapp/board/controller/BoardController.java
  MetanetProject/src/main/java/com/example/myapp/config/SecurityConfig.java
  MetanetProject/src/main/java/com/example/myapp/jwt/JwtAuthenticationFilter.java
  MetanetProject/src/main/java/com/example/myapp/jwt/JwtTokenProvider.java
  MetanetProject/src/main/java/com/example/myapp/jwt/SecurityUtil.java
  MetanetProject/src/main/java/com/example/myapp/jwt/model/JwtToken.java
  MetanetProject/src/main/java/com/example/myapp/jwt/model/RefreshToken.java
  MetanetProject/src/main/java/com/example/myapp/jwt/service/CustomUserDetailsService.java
  MetanetProject/src/main/java/com/example/myapp/jwt/service/RedisTokenService.java
  MetanetProject/src/main/java/com/example/myapp/member/MemberValidator.java
  MetanetProject/src/main/java/com/example/myapp/member/controller/AuthRestController.java
  MetanetProject/src/main/java/com/example/myapp/member/dao/IMemberRepository.java
  MetanetProject/src/main/java/com/example/myapp/member/model/Member.java
  MetanetProject/src/main/java/com/example/myapp/member/service/IMemberService.java
  MetanetProject/src/main/java/com/example/myapp/member/service/MemberService.java
  MetanetProject/src/main/java/com/example/myapp/util/RegexUtil.java
  MetanetProject/src/main/resources/mapper/member/MemberMapper.xml
Labels: feature

#21 [Feature] 장바구니 구현
  MetanetProject/src/main/java/com/example/myapp/cart/controller/CartController.java
  MetanetProject/src/main/java/com/example/myapp/cart/dao/ICartRepository.java
  MetanetProject/src/main/java/com/example/myapp/cart/model/Cart.java
  MetanetProject/src/main/java/com/example/myapp/cart/model/CartDeleteRequest.java
  MetanetProject/src/main/java/com/example/myapp/cart/service/CartService.java
  MetanetProject/src/main/java/com/example/myapp/cart/service/ICartService.java
  MetanetProject/src/main/java/com/example/myapp/member/dao/IMemberRepository.java
  MetanetProject/src/main/resources/mapper/cart/CartMapper.xml
  MetanetProject/src/main/resources/mapper/member/MemberMapper.xml
Labels: feature

#20 [Feature] SMTP를 활용한 비밀번호 재설정
  MetanetProject/src/main/java/com/example/myapp/config/SecurityConfig.java
  MetanetProject/src/main/java/com/example/myapp/member/controller/AuthRestController.java
  MetanetProject/src/main/java/com/example/myapp/member/controller/EmailController.java
  MetanetProject/src/main/java/com/example/myapp/member/dao/IMemberRepository.java
  MetanetProject/src/main/java/com/example/myapp/member/service/IMemberService.java
  MetanetProject/src/main/java/com/example/myapp/member/service/MemberService.java
  MetanetProject/src/main/resources/mapper/member/MemberMapper.xml
Labels: feature

#25 [Feature] 강의 관련 api 추가
  MetanetProject/src/main/java/com/example/myapp/board/controller/BoardController.java
  MetanetProject/src/main/java/com/example/myapp/board/dao/IBoardCategoryRepository.java
  MetanetProject/src/main/java/com/example/myapp/board/dao/IBoardRepository.java
  MetanetProject/src/main/java/com/example/myapp/board/model/Board.java
  MetanetProject/src/main/java/com/example/myapp/board/model/BoardCategory.java
  MetanetProject/src/main/java/com/example/myapp/board/model/BoardUploadFile.java
  MetanetProject/src/main/java/com/example/myapp/board/model/S3Images.java
  MetanetProject/src/main/java/com/example/myapp/board/service/BoardCategoryService.java
  MetanetProject/src/main/java/com/example/myapp/board/service/BoardService.java
  MetanetProject/src/main/java/com/example/myapp/board/service/IBoardCategoryService.java
  MetanetProject/src/main/java/com/example/myapp/board/service/IBoardService.java
  MetanetProject/src/main/java/com/example/myapp/config/SecurityConfig.java
  MetanetProject/src/main/java/com/example/myapp/lecture/controller/LectureRestController.java
  MetanetProject/src/main/java/com/example/myapp/lecture/dao/ILectureRepository.java
  MetanetProject/src/main/java/com/example/myapp/lecture/model/Lecture.java
  MetanetProject/src/main/java/com/example/myapp/lecture/model/LectureFile.java
  MetanetProject/src/main/java/com/example/myapp/lecture/model/LectureId.java
  MetanetProject/src/main/java/com/example/myapp/lecture/service/ILectureService.java
  MetanetProject/src/main/java/com/example/myapp/lecture/service/LectureService.java
  MetanetProject/src/main/java/com/example/myapp/util/RegexUtil.java
  MetanetProject/src/main/java/com/example/myapp/util/S3FileUploader.java
  MetanetProject/src/main/resources/mapper/board/BoardCategoryMapper.xml
  MetanetProject/src/main/resources/mapper/board/BoardMapper.xml
  MetanetProject/src/main/resources/mapper/lecture/LectureMapper.xml
  MetanetProject/src/test/java/com/example/myapp/BoardApplicationTests.java
Labels: feature

#27 [Feature] Refresh token 재발급 로직 구현 #23
  MetanetProject/pom.xml
  MetanetProject/src/main/java/com/example/myapp/jwt/JwtAuthenticationFilter.java
  MetanetProject/src/main/java/com/example/myapp/jwt/JwtTokenProvider.java
  MetanetProject/src/main/java/com/example/myapp/jwt/model/RefreshToken.java
  MetanetProject/src/main/java/com/example/myapp/jwt/service/RedisTokenService.java
  MetanetProject/src/main/java/com/example/myapp/member/controller/AuthRestController.java
  MetanetProject/src/main/java/com/example/myapp/member/dao/IMemberRepository.java
  MetanetProject/src/main/java/com/example/myapp/member/service/IMemberService.java
  MetanetProject/src/main/java/com/example/myapp/member/service/MemberService.java
  MetanetProject/src/main/java/com/example/myapp/util/GlobalExceptionHandler.java
  MetanetProject/src/main/resources/mapper/member/MemberMapper.xml
Labels: feature

#29 [Feature] 관리자 기능 구현
  MetanetProject/src/main/java/com/example/myapp/admin/controller/AdminController.java
  MetanetProject/src/main/java/com/example/myapp/admin/service/AdminService.java
  MetanetProject/src/main/java/com/example/myapp/admin/service/IAdminService.java
  MetanetProject/src/main/java/com/example/myapp/config/SecurityConfig.java
  MetanetProject/src/main/java/com/example/myapp/lecture/dao/ILectureRepository.java
  MetanetProject/src/main/java/com/example/myapp/lecture/model/DeleteLectureRequest.java
  MetanetProject/src/main/java/com/example/myapp/member/dao/IMemberRepository.java
  MetanetProject/src/main/java/com/example/myapp/member/model/DeleteMemberRequest.java
  MetanetProject/src/main/java/com/example/myapp/member/model/MemberResponse.java
  MetanetProject/src/main/resources/mapper/lecture/LectureMapper.xml
  MetanetProject/src/main/resources/mapper/member/MemberMapper.xml
Labels: feature

#31 [Feature] 강의 리뷰 기능 추가
  MetanetProject/src/main/java/com/example/myapp/config/SecurityConfig.java
  MetanetProject/src/main/java/com/example/myapp/review/controller/ReviewControlloer.java
  MetanetProject/src/main/java/com/example/myapp/review/dao/IReviewRepository.java
  MetanetProject/src/main/java/com/example/myapp/review/model/Review.java
  MetanetProject/src/main/java/com/example/myapp/review/service/IReviewService.java
  MetanetProject/src/main/java/com/example/myapp/review/service/ReviewService.java
  MetanetProject/src/main/java/com/example/myapp/util/GetAuthenUser.java
  MetanetProject/src/main/resources/mapper/review/ReviewMapper.xml
Labels: feature

#32 [Feature] QnA 기능 구현
  MetanetProject/pom.xml
  MetanetProject/src/main/java/com/example/myapp/admin/controller/AdminController.java
  MetanetProject/src/main/java/com/example/myapp/cart/dao/ICartRepository.java
  MetanetProject/src/main/java/com/example/myapp/cart/service/CartService.java
  MetanetProject/src/main/java/com/example/myapp/config/SecurityConfig.java
  MetanetProject/src/main/java/com/example/myapp/config/WebSocketConfig.java
  MetanetProject/src/main/java/com/example/myapp/member/dao/IMemberRepository.java
  MetanetProject/src/main/java/com/example/myapp/qna/controller/QnaController.java
  MetanetProject/src/main/java/com/example/myapp/qna/dao/IQnaRepository.java
  MetanetProject/src/main/java/com/example/myapp/qna/model/Answer.java
  MetanetProject/src/main/java/com/example/myapp/qna/model/AnswerDetail.java
  MetanetProject/src/main/java/com/example/myapp/qna/model/AnswerUpdateRequest.java
  MetanetProject/src/main/java/com/example/myapp/qna/model/Notification.java
  MetanetProject/src/main/java/com/example/myapp/qna/model/Question.java
  MetanetProject/src/main/java/com/example/myapp/qna/model/QuestionDetail.java
  MetanetProject/src/main/java/com/example/myapp/qna/model/QuestionSummary.java
  MetanetProject/src/main/java/com/example/myapp/qna/model/QuestionUpdateRequest.java
  MetanetProject/src/main/java/com/example/myapp/qna/service/IQnaService.java
  MetanetProject/src/main/java/com/example/myapp/qna/service/QnaService.java
  MetanetProject/src/main/java/com/example/myapp/util/GetAuthenUser.java
  MetanetProject/src/main/java/com/example/myapp/util/S3FileUploader.java
  MetanetProject/src/main/resources/mapper/member/MemberMapper.xml
  MetanetProject/src/main/resources/mapper/qna/QnaMapper.xml
Labels: feature

#36 AOP 오류 수정 및 logs 테이블 service_name 컬럼 추가
  MetanetProject/src/main/java/com/example/myapp/aop/Log.java
  MetanetProject/src/main/java/com/example/myapp/aop/LogAspect.java
  MetanetProject/src/main/resources/mapper/aop/AopMapper.xml
  MetanetProject/src/main/resources/schema.sql
Labels: feature, fix

#37 [Feature] lecture api 추가 및 file 업로드 오류 수정
  MetanetProject/src/main/java/com/example/myapp/common/response/ResponseCode.java
  MetanetProject/src/main/java/com/example/myapp/common/response/ResponseDto.java
  MetanetProject/src/main/java/com/example/myapp/common/response/ResponseMessage.java
  MetanetProject/src/main/java/com/example/myapp/lecture/controller/LectureRestController.java
  MetanetProject/src/main/java/com/example/myapp/lecture/dao/ILectureRepository.java
  MetanetProject/src/main/java/com/example/myapp/lecture/model/Lecture.java
  MetanetProject/src/main/java/com/example/myapp/lecture/service/ILectureService.java
  MetanetProject/src/main/java/com/example/myapp/lecture/service/LectureService.java
  MetanetProject/src/main/resources/mapper/lecture/LectureMapper.xml
Labels: feature

#39 [Feature] Scheduler를 이용한 메일 전송
  MetanetProject/src/main/java/com/example/myapp/MyappApplication.java
  MetanetProject/src/main/java/com/example/myapp/lecture/LectureScheduler.java
  MetanetProject/src/main/java/com/example/myapp/lecture/dao/ILectureRepository.java
  MetanetProject/src/main/java/com/example/myapp/lecture/model/LectureReminderDto.java
  MetanetProject/src/main/java/com/example/myapp/lecture/model/LectureScheduled.java
  MetanetProject/src/main/java/com/example/myapp/member/service/IMemberService.java
  MetanetProject/src/main/java/com/example/myapp/member/service/MemberService.java
  MetanetProject/src/main/resources/mapper/lecture/LectureMapper.xml
  MetanetProject/src/main/resources/templates/lecture/lecture_reminder.html
  MetanetProject/src/main/resources/templates/lecture/lecture_schedule_mail.html
Labels: feature

#40 [Feature] Review Ui에 답글 작성자 profile 데이터를 가져오도록 수정
  MetanetProject/src/main/java/com/example/myapp/review/controller/ReviewControlloer.java
  MetanetProject/src/main/java/com/example/myapp/review/model/Review.java
  MetanetProject/src/main/resources/mapper/review/ReviewMapper.xml
Labels: feature

#42 [Feature] Lecture Api 기능 수정
  MetanetProject/src/main/java/com/example/myapp/common/response/ResponseCode.java
  MetanetProject/src/main/java/com/example/myapp/common/response/ResponseDto.java
  MetanetProject/src/main/java/com/example/myapp/common/response/ResponseMessage.java
  MetanetProject/src/main/java/com/example/myapp/lecture/controller/LectureRestController.java
  MetanetProject/src/main/java/com/example/myapp/lecture/dao/ILectureRepository.java
  MetanetProject/src/main/java/com/example/myapp/lecture/service/ILectureService.java
  MetanetProject/src/main/java/com/example/myapp/lecture/service/LectureService.java
  MetanetProject/src/main/resources/mapper/lecture/LectureMapper.xml
Labels: feature

#44 [Feature] 마이페이지 구현
  MetanetProject/bin/src/main/resources/mapper/board/BoardCategoryMapper.xml
  MetanetProject/src/main/java/com/example/myapp/account/controller/AccountController.java
  MetanetProject/src/main/java/com/example/myapp/account/dao/IAccountRepository.java
  MetanetProject/src/main/java/com/example/myapp/account/model/AccountLecture.java
  MetanetProject/src/main/java/com/example/myapp/account/model/AdminLectureDashBoard.java
  MetanetProject/src/main/java/com/example/myapp/account/model/AttendLecture.java
  MetanetProject/src/main/java/com/example/myapp/account/model/DueToLecture.java
  MetanetProject/src/main/java/com/example/myapp/account/model/EndLecture.java
  MetanetProject/src/main/java/com/example/myapp/account/model/IngLecture.java
  MetanetProject/src/main/java/com/example/myapp/account/model/MyTechDashBoard.java
  MetanetProject/src/main/java/com/example/myapp/account/model/ProgressLecture.java
  MetanetProject/src/main/java/com/example/myapp/account/service/AccountService.java
  MetanetProject/src/main/java/com/example/myapp/account/service/IAccountService.java
  MetanetProject/src/main/java/com/example/myapp/cart/controller/CartController.java
  MetanetProject/src/main/java/com/example/myapp/jwt/JwtAuthenticationFilter.java
  MetanetProject/src/main/java/com/example/myapp/lecture/controller/LectureRestController.java
  MetanetProject/src/main/java/com/example/myapp/member/controller/AuthRestController.java
  MetanetProject/src/main/java/com/example/myapp/member/controller/EmailController.java
  MetanetProject/src/main/java/com/example/myapp/member/dao/IMemberRepository.java
  MetanetProject/src/main/java/com/example/myapp/member/service/IMemberService.java
  MetanetProject/src/main/java/com/example/myapp/member/service/MemberService.java
  MetanetProject/src/main/java/com/example/myapp/util/GetAuthenUser.java
  MetanetProject/src/main/resources/mapper/account/AccountMapper.xml
  MetanetProject/src/main/resources/mapper/member/MemberMapper.xml
Labels: feature

#46 [Feat, Fix] 수익관련 대시보드 조회 기능 구현 & conflict bug fix
  MetanetProject/src/main/java/com/example/myapp/account/controller/AccountController.java
  MetanetProject/src/main/java/com/example/myapp/account/dao/IAccountRepository.java
  MetanetProject/src/main/java/com/example/myapp/account/service/AccountService.java
  MetanetProject/src/main/java/com/example/myapp/config/SecurityConfig.java
  MetanetProject/src/main/java/com/example/myapp/lecture/controller/LectureRestController.java
  MetanetProject/src/main/java/com/example/myapp/lecture/dao/ILectureRepository.java
  MetanetProject/src/main/java/com/example/myapp/lecture/model/LectureRevenueDto.java
  MetanetProject/src/main/java/com/example/myapp/lecture/model/MonthlySalesDto.java
  MetanetProject/src/main/java/com/example/myapp/lecture/model/MonthlySalesResponse.java
  MetanetProject/src/main/java/com/example/myapp/member/dao/IMemberRepository.java
  MetanetProject/src/main/java/com/example/myapp/member/service/MemberService.java
  MetanetProject/src/main/resources/mapper/lecture/LectureMapper.xml
Labels: feature, fix

#49 [Feature] 웹소켓을 활용한 실시간 알림 기능
  MetanetProject/src/main/java/com/example/myapp/config/SecurityConfig.java
  MetanetProject/src/main/java/com/example/myapp/config/WebSocketConfig.java
  MetanetProject/src/main/java/com/example/myapp/jwt/JwtAuthenticationFilter.java
  MetanetProject/src/main/java/com/example/myapp/member/dao/IMemberRepository.java
  MetanetProject/src/main/java/com/example/myapp/qna/dao/IQnaRepository.java
  MetanetProject/src/main/java/com/example/myapp/qna/service/QnaService.java
  MetanetProject/src/main/resources/mapper/member/MemberMapper.xml
  MetanetProject/src/main/resources/mapper/qna/QnaMapper.xml
Labels: feature

#48 [Feature] 엑셀파일 입력 기능 추가
  MetanetProject/pom.xml
  MetanetProject/src/main/java/com/example/myapp/excel/controller/ExcelController.java
  MetanetProject/src/main/java/com/example/myapp/excel/model/MemberForExcel.java
  MetanetProject/src/main/java/com/example/myapp/lecture/dao/ILectureRepository.java
  MetanetProject/src/main/java/com/example/myapp/lecture/model/LectureList.java
  MetanetProject/src/main/java/com/example/myapp/lecture/service/ILectureService.java
  MetanetProject/src/main/java/com/example/myapp/lecture/service/LectureService.java
  MetanetProject/src/main/java/com/example/myapp/member/dao/IMemberRepository.java
  MetanetProject/src/main/java/com/example/myapp/member/service/IMemberService.java
  MetanetProject/src/main/java/com/example/myapp/member/service/MemberService.java
  MetanetProject/src/main/resources/mapper/lecture/LectureMapper.xml
  MetanetProject/src/main/resources/mapper/member/MemberMapper.xml
  MetanetProject/src/main/resources/template/student-template.xlsx
Labels: feature

#52 [Fix] JwtAuthenticationFilter에 누락된 url 추가
  MetanetProject/src/main/java/com/example/myapp/config/SecurityConfig.java
  MetanetProject/src/main/java/com/example/myapp/jwt/JwtAuthenticationFilter.java
  MetanetProject/src/main/java/com/example/myapp/lecture/controller/LectureRestController.java
Labels: fix

#53 [Feature] 수료 완료 후 html을 pdf 로 변환하여 다운로드 구현
  MetanetProject/pom.xml
  MetanetProject/src/main/java/com/example/myapp/certification/controller/CertificationController.java
  MetanetProject/src/main/java/com/example/myapp/certification/dao/ICertificationRepository.java
  MetanetProject/src/main/java/com/example/myapp/certification/dto/Certification.java
  MetanetProject/src/main/java/com/example/myapp/certification/service/CertificationService.java
  MetanetProject/src/main/java/com/example/myapp/certification/service/ICertificationService.java
  MetanetProject/src/main/java/com/example/myapp/common/response/ResponseDto.java
  MetanetProject/src/main/resources/mapper/certification/CertificationMapper.xml
  MetanetProject/src/main/resources/pdf/NanumBarunGothic.ttf
  MetanetProject/src/main/resources/pdf/check.jpg
Labels: feature

#58 [fix] 강의 강사 이름 가져오도록 추가
  MetanetProject/src/main/java/com/example/myapp/lecture/model/Lecture.java
  MetanetProject/src/main/resources/mapper/lecture/LectureMapper.xml
Labels: fix

#60 [Fix] 질문 상세 조회 시 삭제된 답변은 제외하도록 수정
  MetanetProject/src/main/resources/mapper/qna/QnaMapper.xml
Labels: fix

#67 [Refactor] zoom webhook uri 수정 & uri 권한 수정
  MetanetProject/src/main/java/com/classpick/web/config/SecurityConfig.java
  MetanetProject/src/main/java/com/classpick/web/jwt/JwtAuthenticationFilter.java
  MetanetProject/src/main/java/com/classpick/web/lecture/controller/LectureRestController.java
  MetanetProject/src/main/java/com/classpick/web/review/controller/ReviewControlloer.java
  MetanetProject/src/main/java/com/classpick/web/zoom/controller/ZoomController.java
  MetanetProject/src/main/resources/mapper/qna/QnaMapper.xml
Labels: feature, fix, refactor

#74 [Feat] 알림 전송 시 lectureId, questionId 추가 전송
  MetanetProject/src/main/java/com/classpick/web/qna/model/Notification.java
  MetanetProject/src/main/java/com/classpick/web/qna/service/QnaService.java
Labels: feature

#76 [Fix] AOP 포인트컷 표현식의 패키지명 수정
  MetanetProject/src/main/java/com/classpick/web/aop/LogAspect.java
Labels: fix

#70 [Fix] 회원가입 로직 재수정
  MetanetProject/src/main/java/com/classpick/web/member/controller/AuthRestController.java
  MetanetProject/src/main/java/com/classpick/web/member/dao/IMemberRepository.java
  MetanetProject/src/main/java/com/classpick/web/member/service/IMemberService.java
  MetanetProject/src/main/java/com/classpick/web/member/service/MemberService.java
  MetanetProject/src/main/resources/mapper/member/MemberMapper.xml
Labels: fix

#77 회원 가입 및 마이 페이지 로직 수정
  MetanetProject/src/main/java/com/classpick/web/account/controller/AccountController.java
  MetanetProject/src/main/java/com/classpick/web/account/dao/IAccountRepository.java
  MetanetProject/src/main/java/com/classpick/web/account/model/AccountMembers.java
  MetanetProject/src/main/java/com/classpick/web/account/model/Pay.java
  MetanetProject/src/main/java/com/classpick/web/account/model/UpdateMember.java
  MetanetProject/src/main/java/com/classpick/web/account/service/AccountService.java
  MetanetProject/src/main/java/com/classpick/web/account/service/IAccountService.java
  MetanetProject/src/main/java/com/classpick/web/member/controller/AuthRestController.java
  MetanetProject/src/main/java/com/classpick/web/member/controller/EmailController.java
  MetanetProject/src/main/java/com/classpick/web/member/dao/IMemberRepository.java
  MetanetProject/src/main/java/com/classpick/web/member/model/ToolBarMember.java
  MetanetProject/src/main/java/com/classpick/web/member/service/IMemberService.java
  MetanetProject/src/main/java/com/classpick/web/member/service/MemberService.java
  MetanetProject/src/main/resources/mapper/account/AccountMapper.xml
  MetanetProject/src/main/resources/mapper/member/MemberMapper.xml
Labels: feature, fix

#80 [Fix] 장바구니 & MemberService 오류 수정
  MetanetProject/src/main/java/com/classpick/web/cart/service/CartService.java
  MetanetProject/src/main/java/com/classpick/web/member/controller/AuthRestController.java
  MetanetProject/src/main/java/com/classpick/web/member/service/MemberService.java
  MetanetProject/src/main/resources/mapper/cart/CartMapper.xml
Labels: fix

#85 [Fix] AOP 수정
  MetanetProject/src/main/java/com/classpick/web/aop/Log.java
  MetanetProject/src/main/java/com/classpick/web/aop/LogAspect.java
  MetanetProject/src/main/resources/mapper/aop/AopMapper.xml
Labels: fix

#86 [Fix] Remove response status (#84)
  MetanetProject/src/main/java/com/classpick/web/aop/Log.java
  MetanetProject/src/main/java/com/classpick/web/aop/LogAspect.java
  MetanetProject/src/main/java/com/classpick/web/lecture/model/Lecture.java
  MetanetProject/src/main/resources/mapper/aop/AopMapper.xml
Labels: fix

#89 [Fix] 강의 생성기능 수리
  MetanetProject/src/main/java/com/classpick/web/excel/controller/ExcelController.java
  MetanetProject/src/main/java/com/classpick/web/lecture/controller/LectureRestController.java
  MetanetProject/src/main/java/com/classpick/web/lecture/dao/ILectureRepository.java
  MetanetProject/src/main/java/com/classpick/web/lecture/model/Lecture.java
  MetanetProject/src/main/java/com/classpick/web/lecture/model/LectureList.java
  MetanetProject/src/main/java/com/classpick/web/lecture/model/Tag.java
  MetanetProject/src/main/java/com/classpick/web/lecture/service/ILectureService.java
  MetanetProject/src/main/java/com/classpick/web/lecture/service/LectureService.java
  MetanetProject/src/main/java/com/classpick/web/zoom/model/ZoomDate.java
  MetanetProject/src/main/java/com/classpick/web/zoom/model/ZoomMeetingRequest.java
  MetanetProject/src/main/resources/mapper/lecture/LectureMapper.xml
Labels: feature, fix

#91 [Fix] 장바구니 추가 쿼리 수정
  MetanetProject/src/main/resources/mapper/cart/CartMapper.xml
Labels: fix

#87 [Fix] 관리자 대시보드 API 추가 및 마이페이지 관련 API 수정
  MetanetProject/src/main/java/com/classpick/web/account/model/AccountLecture.java
  MetanetProject/src/main/java/com/classpick/web/account/model/Pay.java
  MetanetProject/src/main/java/com/classpick/web/admin/controller/AdminController.java
  MetanetProject/src/main/java/com/classpick/web/admin/model/AdminDashboard.java
  MetanetProject/src/main/java/com/classpick/web/admin/model/LectureDashboard.java
  MetanetProject/src/main/java/com/classpick/web/admin/model/MemDashboard.java
  MetanetProject/src/main/java/com/classpick/web/admin/model/PercentDashboard.java
  MetanetProject/src/main/java/com/classpick/web/admin/model/StudentTeacherDashboard.java
  MetanetProject/src/main/java/com/classpick/web/admin/service/AdminService.java
  MetanetProject/src/main/java/com/classpick/web/admin/service/IAdminService.java
  MetanetProject/src/main/java/com/classpick/web/certification/controller/CertificationController.java
  MetanetProject/src/main/java/com/classpick/web/certification/dao/ICertificationRepository.java
  MetanetProject/src/main/java/com/classpick/web/certification/service/CertificationService.java
  MetanetProject/src/main/java/com/classpick/web/certification/service/ICertificationService.java
  MetanetProject/src/main/java/com/classpick/web/config/SecurityConfig.java
  MetanetProject/src/main/java/com/classpick/web/lecture/dao/ILectureRepository.java
  MetanetProject/src/main/java/com/classpick/web/member/controller/AuthRestController.java
  MetanetProject/src/main/java/com/classpick/web/member/dao/IMemberRepository.java
  MetanetProject/src/main/java/com/classpick/web/member/model/MemberResponse.java
  MetanetProject/src/main/java/com/classpick/web/member/service/IMemberService.java
  MetanetProject/src/main/java/com/classpick/web/member/service/MemberService.java
  MetanetProject/src/main/resources/mapper/account/AccountMapper.xml
  MetanetProject/src/main/resources/mapper/lecture/LectureMapper.xml
  MetanetProject/src/main/resources/mapper/member/MemberMapper.xml
Labels: feature, fix

#92 [Feature] 권한 처리 BE 구현
  MetanetProject/src/main/java/com/classpick/web/common/response/ResponseDto.java
  MetanetProject/src/main/java/com/classpick/web/config/SecurityConfig.java
  MetanetProject/src/main/java/com/classpick/web/error/ErrorController.java
Labels: feature

#94 [Feature] 장바구니 담기 조건 추가, 강의 자료 다운로드 조건 추가
  MetanetProject/src/main/java/com/classpick/web/cart/controller/CartController.java
  MetanetProject/src/main/java/com/classpick/web/cart/service/CartService.java
  MetanetProject/src/main/java/com/classpick/web/lecture/controller/LectureRestController.java
  MetanetProject/src/main/java/com/classpick/web/lecture/dao/ILectureRepository.java
  MetanetProject/src/main/java/com/classpick/web/lecture/service/ILectureService.java
  MetanetProject/src/main/java/com/classpick/web/lecture/service/LectureService.java
  MetanetProject/src/main/java/com/classpick/web/review/model/Review.java
  MetanetProject/src/main/resources/mapper/lecture/LectureMapper.xml
  MetanetProject/src/main/resources/mapper/review/ReviewMapper.xml
Labels: feature

#101 [Test] 테스트 커버리지 측정 및 통합 테스트 진행
  MetanetProject/pom.xml
  MetanetProject/src/main/java/com/classpick/web/account/service/AccountService.java
  MetanetProject/src/main/java/com/classpick/web/admin/service/AdminService.java
  MetanetProject/src/main/java/com/classpick/web/config/RestTemplateConfig.java
  MetanetProject/src/main/java/com/classpick/web/member/service/MemberService.java
  MetanetProject/src/main/java/com/classpick/web/zoom/service/ZoomService.java
  MetanetProject/src/test/java/com/classpick/web/account/AccountServiceTest.java
  MetanetProject/src/test/java/com/classpick/web/admin/AdminServiceTest.java
  MetanetProject/src/test/java/com/classpick/web/cart/CartControllerTest.java
  MetanetProject/src/test/java/com/classpick/web/cart/CartServiceTest.java
  MetanetProject/src/test/java/com/classpick/web/certification/CertificationServiceTest.java
  MetanetProject/src/test/java/com/classpick/web/lecture/LectureServiceTest.java
  MetanetProject/src/test/java/com/classpick/web/member/MemberServiceTest.java
  MetanetProject/src/test/java/com/classpick/web/qna/QnaServiceTest.java
  MetanetProject/src/test/java/com/classpick/web/review/ReviewServiceTest.java
  MetanetProject/src/test/java/com/classpick/web/zoom/ZoomServiceTest.java
Labels: Test
